# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'cocoapodProject' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cocoapodProject
	pod 'CWStatusBarNotification', '~> 2.3'
	pod 'FontAwesomeKit', '~> 2.2.0'
end
